### ISSUE TITLE
about M5OnScreenKeyboard

### ISSUE THREAD

**Issue by drisshaou** [lovyan03/M5OnScreenKeyboard#1]
Hello,

I want to know if it is possible to make it AZERTY and extended latin for french character?

Thanks.

**Comment by lovyan03** [comment]
I just added "useOver 0x80 Chars" setting.

`  m5osk.useOver0x80Chars = true; `
// The number of panels will increase.

But I do not understand the chars of Europe.
I can not make an appropriate char table.
Please propose.

**Comment by drisshaou** [comment]
Hello,

Thanks for answering and excuse my poor english, i'm very new on arduino it's c/c++ code if i'm not wrong, i use Process (program) to create a font .vlw and M5.Lcd.loadFont, (because to generate a GFX custom font from Adafruit generator for extended latin are not available yet) so that the only way i found to have unicode extended latin characters, the problem that i have not understand is some character like "€" is 0xE2 0x82 0xAC or "é" is 0xC3 0xA9 but how to put them on char array ?

**Comment by lovyan03** [comment]
This keyboard is ASCII characters only.
It is mainly used for entering URL or Wi-Fi password.
